server: 
 port: 8761
eureka:  
 instance:  
  hostname: localhost
 server:  
  enable-self-preservation: false
  eviction-interval-timer-in-ms: 30000
 client:  
  registry-fetch-interval-seconds: 30
  registerWithEureka: false
  fetchRegistry: false
 serviceUrl:  
  defaultZone: http://localhost:8761/eureka/
management:  
 security: 
  enabled: false
