server: 
  port: 8762
eureka: 
  instance:  
   lease-renewal-interval-in-seconds: 15
   hostname: localhost
  client: 
   registry-fetch-interval-seconds: 30
   serviceUrl: 
     defaultZone: http://localhost:8761/eureka/
spring: 
 application: 
  name: shiyan

